# Generated by Django 4.1.5 on 2023-06-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_entry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_database',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='account_database',
            name='notes',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
