# Generated by Django 4.1.5 on 2023-06-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_entry', '0002_alter_account_database_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_database',
            name='account',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='account_database',
            name='category',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='account_database',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
